github.com:
    users:
        prajitdas:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: prajitdas
